### ISSUE TITLE
I've done a pull request by adding more country card

### ISSUE THREAD

**Issue by FSBM** [adarshlkdev/GlobeScout#7]
I've added a country card for Madagascar :
Please assign this under hacktober.

**Comment by FSBM** [comment]
Also if you want me to add more country cards. I'll do it if you assign it to me.

**Comment by adarshlkdev** [comment]
That's great but it is not necessary. If you want to contribute in this repo pls make some impactful changes. 
**Steps for adding your pr under hacktoberfest =>**

1.   Follow me 
2.  Give a star on this Repo
